### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Globik** [kentor/invalidate-module#1]
Nor simply nor with path.resolve nor require.resolve does not work. Your module is error prone.
I am on linux, nodejs v7.10.0

**Comment by kentor** [comment]
Give me a code sample

**Comment by Globik** [comment]
var inv=require('invalidate-module')
var count=require('./count.js')
console.log(count.count())
console.log(count.count())
inv('./count.js')
console.log(count.count())
console.log(count.count())
// no effect just shows to console 1 2 3 4
And count.js:
var cnt=0;

var count=()=>{
return cnt++;
}
module.exports={count}
And like you recomend in docs I also tried invalidate module via path.resolve() that throws an error that something charCode at is not blah blah suitable.
inv(require.resolve('./count.js')) also throws an error.

**Comment by kentor** [comment]
That isn't the correct usage. Perhaps I need to document better but this module does not invalidate the state of an already imported module. Something like this would work:

```js
var inv = require('invalidate-module')
var count = require('./count.js')
console.log(count.count())
console.log(count.count())
inv(require.resolve('./count.js'))
count = require('./count.js') // <-- you need to re-require the module which will return a new instance of the exports
console.log(count.count())
console.log(count.count())
```

**Comment by Globik** [comment]
Ah so, in the morning I give it a try. Yes, in docs there is no mention about it, sorry I misunderstood.

**Comment by Globik** [comment]
Apropos, there are some unreplied issues about hot reloading.
Please visit this and see
https://github.com/kentor/kentor.me/issues
Any thought?

**Comment by Globik** [comment]
In fact it rerequires a  module and that's with it. Just overrides a variable but not invalidates. I don't know but I think a real hot reloading system really invalidate a module.

**Comment by Globik** [comment]
I mean with a lucky I can do something like this
Without invalidate-module.js:
var count=require('./count.js')
console.log(count.count())
console.log(count.count())
var count=require('./count.js')

console.log(count.count())
console.log(count.count())
And that shows me successfully:
0
1
0
1
So what the meaning of invalidate-module.js? Those twistls and swistls around require.cache[m]??
Yes, it deletes something there(runned in debug mode) but what s practice use I don't know.
So I decided to write my own module by name hotreloader.js
It do the simple test with count() just fine.

**Comment by Globik** [comment]
In other words should be the same effect as from delete count.count or
delete module.constructor._cache['full_pass_module.js'].exports.count
